const INFLOW_CATEGORY_GROUP = "Inflow";
const UNCATEGORISED_CATEGORY_GROUP = "Uncategorised";

export const PROTECTED_CATEGORY_GROUP_NAMES = [
  INFLOW_CATEGORY_GROUP,
  UNCATEGORISED_CATEGORY_GROUP,
] as const;
