openapi: 3.0.3
info:
  title: Budgie API
  version: 1.0.0

paths:
  # Hydration
  /budget/snapshot:
    $ref: "./paths/hydration/snapshot.yml"

  # Memos
  /budget/memo/{id}:
    $ref: "./paths/memos/modify.yml"

  # Categories
  /budget/categories:
    $ref: "./paths/categories/create.yml"
  /budget/categories/{categoryId}:
    $ref: "./paths/categories/modify.yml"

  # Category groups
  /budget/category-groups/{categoryGroupId}:
    $ref: "./paths/categoryGroups/modify.yml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # Entities
    CategoryUser:
      $ref: "./schemas/entities/category.yml#/CategoryUser"
    CategorySystem:
      $ref: "./schemas/entities/category.yml#/CategorySystem"
    CategoryGroupUser:
      $ref: "./schemas/entities/categoryGroup.yml#/CategoryGroupUser"
    CategoryGroupSystem:
      $ref: "./schemas/entities/categoryGroup.yml#/CategoryGroupSystem"
    Month:
      $ref: "./schemas/entities/month.yml#/Month"
    Account:
      $ref: "./schemas/entities/account.yml#/Account"
    Transaction:
      $ref: "./schemas/entities/transaction.yml#/Transaction"
    Payee:
      $ref: "./schemas/entities/payee.yml#/Payee"
    Memo:
      $ref: "./schemas/entities/memo.yml#/Memo"

    # Hydration
    BudgetSnapshot:
      $ref: "./schemas/hydration/budgetSnapshot.yml#/BudgetSnapshot"

    #----------
    # Requests
    #----------

    # Category requests
    CreateCategoryRequest:
      $ref: "./schemas/requests/categories/createCategory.yml#/CreateCategoryRequest"
    UpdateCategoryRequest:
      $ref: "./schemas/requests/categories/updateCategory.yml#/UpdateCategoryRequest"
    DeleteCategoryRequest:
      $ref: "./schemas/requests/categories/deleteCategory.yml#/DeleteCategoryRequest"

    #----------
    # Responses
    #----------

    # Category responses
    CreateCategoryResponse:
      $ref: "./schemas/responses/categories/createCategory.yml#/CreateCategoryResponse"
    UpdateCategoryResponse:
      $ref: "./schemas/responses/categories/updateCategory.yml#/UpdateCategoryResponse"
    DeleteCategoryResponse:
      $ref: "./schemas/responses/categories/deleteCategory.yml#/DeleteCategoryResponse"
    CategoryPositionPatch:
      $ref: "./schemas/responses/categories/patches/categoryPositionPatch.yml#/CategoryPositionPatch"

    # Category Group responses
    CreateCategoryGroupResponse:
      $ref: "./schemas/responses/categoryGroups/createCategoryGroup.yml#/CreateCategoryGroupResponse"
    UpdateCategoryGroupResponse:
      $ref: "./schemas/responses/categoryGroups/updateCategoryGroup.yml#/UpdateCategoryGroupResponse"
    DeleteCategoryGroupResponse:
      $ref: "./schemas/responses/categoryGroups/deleteCategoryGroup.yml#/DeleteCategoryGroupResponse"
    CategoryGroupPositionPatch:
      $ref: "./schemas/responses/categoryGroups/patches/categoryGroupPositionPatch.yml#/CategoryGroupPositionPatch"

    # Edit memo response
    EditMemoResponse:
      $ref: "./schemas/responses/memo/editMemo.yml#/EditMemoResponse"
