/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/budget/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full budget snapshot
         * @description Fetches a snapshot containing pre-indexed entities for frontend consumption for the authenticated user.
         */
        get: operations["getBudgetSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/memo/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit memo
         * @description Edit memo for the authenticated user.
         */
        patch: operations["editMemo"];
        trace?: never;
    };
    "/budget/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create category
         * @description Creates a new budget category inside an existing category group owned by the user, dynamically  calculating its sorting position, and automatically initialising accompanying zero-value  budget timeline months derived from existing system or user category milestones.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete category
         * @description Deletes a category reassigning transactions and assigned money
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /**
         * Update a category
         * @description Updates a user category. The category may be renamed, moved to another category group, and/or reordered within its category group.
         *     When a category is moved or reordered, the response contains position patches for all affected categories so clients can reconcile their local state without fetching the entire category collection.
         *     The category returned in `updated.category` represents the primary category modified by the operation. The `updated.categories` array contains patches for categories whose position or category group changed as a result of the operation.
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/budget/category-groups/{categoryGroupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a category group
         * @description Deletes a category group. If the group contains transactions, an inheriting category must be provided and transactions will be reassigned. Remaining assigned funds from deleted categories are returned to Ready to Assign.
         */
        delete: operations["deleteCategoryGroup"];
        options?: never;
        head?: never;
        /**
         * Update a category group
         * @description Updates a user category group. The category group may be renamed or moved.
         *     When a category group is moved or reordered, the response contains position patches for all affected category groups so clients can reconcile their local state without fetching the entire category group collection.
         *     The category group returned in `updated.categoryGroup` represents the primary category group modified by the operation. The `updated.categoryGroups` array contains patches for category groups whose position or category group changed as a result of the operation.
         */
        patch: operations["updateCategoryGroup"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description User-created budget category. */
        CategoryUser: {
            /**
             * Format: uuid
             * @description Unique identifier of the category.
             * @example category_123
             */
            id: string;
            /**
             * Format: uuid
             * @description Identifier of the category group containing this category.
             * @example category_group_123
             */
            categoryGroupId: string;
            /**
             * @description Name of the category.
             * @example Groceries
             */
            name: string;
            /**
             * @description Zero-based position of the category within its category group.
             * @example 0
             */
            position: number;
        };
        /** @description System-defined budget category. */
        CategorySystem: {
            /**
             * Format: uuid
             * @description Unique identifier of the system category.
             * @example category_rta
             */
            id: string;
            /**
             * Format: uuid
             * @description Identifier of the category group containing this category.
             * @example category_group_rta
             */
            categoryGroupId: string;
            /**
             * @description Name of the system category.
             * @example Ready to Assign
             */
            name: string;
        };
        CategoryGroupUser: {
            /** Format: uuid */
            id: string;
            name: string;
            position: number;
        };
        CategoryGroupSystem: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Month: {
            id: string;
            categoryId: string;
            month: components["schemas"]["MonthKey"];
            activity: number;
            assigned: number;
            available: number;
        };
        Account: {
            id: string;
            name: string;
            position: number;
            open: boolean;
            /** @enum {string} */
            type: "BANK" | "CREDIT_CARD";
            deletable: boolean;
            balance: number;
        };
        Transaction: components["schemas"]["TransactionNormal"] | components["schemas"]["TransactionTransfer"];
        Payee: {
            id: string;
            name: string;
            /** @enum {string} */
            origin: "SYSTEM" | "USER";
            defaultCategoryId: string | null;
            includeInPayeeList: boolean;
            automaticallyCategorisePayee: boolean;
        };
        Memo: {
            id: string;
            month: components["schemas"]["MonthKey"];
            content: string;
        };
        /**
         * @description Complete budget state required to hydrate the frontend. Entities are indexed by ID for efficient lookup and state reconciliation.
         * @example {
         *       "categoryGroups": {
         *         "user": {
         *           "cg_1": {
         *             "id": "cg_1",
         *             "name": "Food",
         *             "position": 1
         *           }
         *         },
         *         "inflow": {
         *           "id": "inflow",
         *           "name": "Inflow"
         *         },
         *         "uncategorised": {
         *           "id": "uncategorised",
         *           "name": "Uncategorised"
         *         }
         *       },
         *       "categories": {
         *         "user": {
         *           "cat_1": {
         *             "id": "cat_1",
         *             "name": "Groceries",
         *             "position": 1,
         *             "categoryGroupId": "cg_1"
         *           }
         *         },
         *         "rta": {
         *           "id": "rta",
         *           "name": "Ready to Assign",
         *           "categoryGroupId": "cg_1"
         *         },
         *         "uncategorised": {
         *           "id": "uncategorised",
         *           "name": "Uncategorised",
         *           "categoryGroupId": "cg_1"
         *         }
         *       },
         *       "months": {
         *         "month_1": {
         *           "id": "month_1",
         *           "categoryId": "cat_1",
         *           "month": "2025-12",
         *           "activity": 100,
         *           "assigned": 200,
         *           "available": 100
         *         }
         *       },
         *       "accounts": {
         *         "acc_1": {
         *           "id": "acc_1",
         *           "name": "Checking",
         *           "position": 1,
         *           "open": true,
         *           "type": "BANK",
         *           "deletable": true,
         *           "balance": 1000
         *         }
         *       },
         *       "transactions": {
         *         "tx_1": {
         *           "id": "tx_1",
         *           "accountId": "acc_1",
         *           "categoryId": "cat_1",
         *           "payeeId": "pay_1",
         *           "date": "2025-12-13T00:00:00.000Z",
         *           "memo": "Tesco",
         *           "inflow": 0,
         *           "outflow": 12.34
         *         }
         *       },
         *       "payees": {
         *         "pay_1": {
         *           "id": "pay_1",
         *           "name": "Tesco",
         *           "origin": "USER",
         *           "defaultCategoryId": "cat_1",
         *           "includeInPayeeList": true,
         *           "automaticallyCategorisePayee": true
         *         }
         *       },
         *       "memosByMonth": {
         *         "2025-12": {
         *           "id": "memo_1",
         *           "month": "2025-12",
         *           "content": "Holiday budget"
         *         }
         *       },
         *       "monthKeys": [
         *         "2025-12"
         *       ]
         *     }
         */
        BudgetSnapshot: {
            categoryGroups: {
                user: {
                    [key: string]: components["schemas"]["CategoryGroupUser"];
                };
                inflow: components["schemas"]["CategoryGroupSystem"];
                uncategorised: components["schemas"]["CategoryGroupSystem"];
            };
            categories: {
                user: {
                    [key: string]: components["schemas"]["CategoryUser"];
                };
                rta: components["schemas"]["CategorySystem"];
                uncategorised: components["schemas"]["CategorySystem"];
            };
            months: {
                [key: string]: components["schemas"]["Month"];
            };
            accounts: {
                [key: string]: components["schemas"]["Account"];
            };
            transactions: {
                [key: string]: components["schemas"]["Transaction"];
            };
            payees: {
                [key: string]: components["schemas"]["Payee"];
            };
            /** @description Map of MonthKey (YYYY-MM) → Memo (1:1 invariant) */
            memosByMonth: {
                [key: string]: components["schemas"]["Memo"];
            };
            monthKeys: components["schemas"]["MonthKey"][];
        };
        /** @description Request to create a new user category. */
        CreateCategoryRequest: {
            /** @description Name of the category. */
            name: string;
            /**
             * Format: uuid
             * @description ID of the category group the category belongs to.
             */
            categoryGroupId: string;
        };
        /** @description Request to update a user category. Only the fields that need to be changed need to be provided. */
        UpdateCategoryRequest: {
            /** @description New name for the category. */
            name?: string;
            /**
             * Format: uuid
             * @description ID of the category group to move the category into.
             */
            categoryGroupId?: string;
            /** @description New zero-based position of the category within its group. */
            position?: number;
        };
        /** @description Request to delete a user category. If the category has transactions, an inheriting category must be provided to receive those transactions. */
        DeleteCategoryRequest: {
            /**
             * Format: uuid
             * @description ID of the category that will inherit transactions from the deleted category.
             */
            inheritingCategoryId?: string;
        };
        /** @description Result of creating a user category, including the newly created category and its associated months. */
        CreateCategoryResponse: {
            created: {
                category: components["schemas"]["CategoryUser"];
                /** @description Newly created months keyed by month id. */
                months: {
                    [key: string]: components["schemas"]["Month"];
                };
            };
        };
        /**
         * @description Response returned after updating a user category.
         *     The response uses a patch-based state reconciliation model. The updated category is returned in full, while any other categories affected by reordering or moving the category are returned as position patches.
         */
        UpdateCategoryResponse: {
            updated: {
                category: components["schemas"]["CategoryUser"];
                /**
                 * @description Partial updates for categories affected by the operation. Each entry contains the category's ID, new position, and category group ID.
                 *     This array is empty when no other categories are affected, such as during a rename-only operation.
                 */
                categories: components["schemas"]["CategoryPositionPatch"][];
            };
        };
        /** @description Response returned after deleting a user category. Includes the deleted category and months, along with categories, transactions, and months affected by the deletion. */
        DeleteCategoryResponse: {
            deleted: {
                category: components["schemas"]["CategoryUser"];
                /** @description Deleted months keyed by month id. */
                months: {
                    [key: string]: components["schemas"]["Month"];
                };
            };
            updated: {
                /** @description Partial updates for categories affected by the operation. Each entry contains the category's ID, new position, and category group ID. */
                categories: components["schemas"]["CategoryPositionPatch"][];
                /** @description Updated transactions keyed by transaction id. */
                transactions: {
                    [key: string]: components["schemas"]["Transaction"];
                };
                /** @description Updated months keyed by month id. */
                months: {
                    [key: string]: components["schemas"]["Month"];
                };
            };
        };
        /** @description Partial category state returned when a category reorder or category-group change affects the category's position or group. */
        CategoryPositionPatch: {
            /**
             * Format: uuid
             * @description Unique identifier of the affected category.
             * @example category_123
             */
            id: string;
            /**
             * @description The category's new zero-based position within its category group.
             * @example 2
             */
            position: number;
            /**
             * Format: uuid
             * @description Unique identifier of the category's category group.
             * @example category_group_123
             */
            categoryGroupId: string;
        };
        /** @description Response returned after creating a user category group. Contains the newly created category group. */
        CreateCategoryGroupResponse: {
            created: {
                categoryGroup: components["schemas"]["CategoryGroupUser"];
            };
        };
        UpdateCategoryGroupResponse: {
            updated: {
                categoryGroup: components["schemas"]["CategoryGroupUser"];
                /** @description Position patches for category groups affected by the update. The primary category group is returned separately in `categoryGroup`. */
                categoryGroups: components["schemas"]["CategoryGroupPositionPatch"][];
            };
        };
        /** @description Response returned after deleting a category group. Contains the deleted category group and related entities, together with the entities affected by the deletion for incremental client-side state reconciliation. */
        DeleteCategoryGroupResponse: {
            deleted: {
                categoryGroup: components["schemas"]["CategoryGroupUser"];
                /** @description Deleted categories keyed by category id. */
                categories: {
                    [key: string]: components["schemas"]["CategoryUser"];
                };
                /** @description Deleted months keyed by month id. */
                months: {
                    [key: string]: components["schemas"]["Month"];
                };
            };
            updated: {
                /** @description Position patches for category groups affected by the deletion. */
                categoryGroups: components["schemas"]["CategoryGroupPositionPatch"][];
                /** @description Updated transactions keyed by transaction id. */
                transactions: {
                    [key: string]: components["schemas"]["TransactionNormal"];
                };
                /** @description Updated months keyed by month id. */
                months: {
                    [key: string]: components["schemas"]["Month"];
                };
            };
        };
        CategoryGroupPositionPatch: {
            /** Format: uuid */
            id: string;
            position: number;
        };
        /** @description Response returned after updating a memo. Contains the updated memo. */
        EditMemoResponse: components["schemas"]["Memo"];
        /** @example 2025-12 */
        MonthKey: string;
        TransactionNormal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "normal";
            id: string;
            accountId: string;
            categoryId: string;
            payeeId: string | null;
            /** Format: date-time */
            date: string;
            memo: string;
            inflow: number;
            outflow: number;
        };
        TransactionTransfer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transfer";
            id: string;
            accountId: string;
            payeeId: string | null;
            /** Format: date-time */
            date: string;
            memo: string;
            inflow: number;
            outflow: number;
            transferAccountId: string;
            transferTransactionId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBudgetSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSnapshot"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description Successfully updated memo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memo"];
                };
            };
            /** @description Bad request (invalid input or malformed payload) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memo not found or owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The name of the category (leading and trailing whitespace will be trimmed).
                     * @example Groceries
                     */
                    name: string;
                    /**
                     * @description Target parent Category Group UUID.
                     * @example 8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d
                     */
                    categoryGroupId: string;
                };
            };
        };
        responses: {
            /** @description Successfully created category and tracking months */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCategoryResponse"];
                };
            };
            /** @description Unauthorised (missing or expired session token) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category group not found or unowned by user context */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict (a category with this normalised name already exists within this category group) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the category to delete. */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The category that will inherit the transactions assigned to the deleted category.
                     * @example 8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d
                     */
                    inheritingCategoryId?: string;
                };
            };
        };
        responses: {
            /** @description Category deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCategoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid category deletion request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the category to update.
                 * @example 8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d
                 */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The new name for the category.
                     * @example Holiday
                     */
                    name?: string;
                    /**
                     * @description The ID of the category group to move the category into.
                     * @example 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d
                     */
                    categoryGroupId?: string;
                    /**
                     * @description The zero-based position of the category within its category group.
                     * @example 2
                     */
                    position?: number;
                };
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCategoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A category with the requested name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid category update request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCategoryGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the category group to delete. */
                categoryGroupId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description The category that will inherit transactions from categories within the deleted category group.
                     * @example 8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d
                     */
                    inheritingCategoryId?: string;
                };
            };
        };
        responses: {
            /** @description Category group deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCategoryGroupResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid category group deletion request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCategoryGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the category group to update.
                 * @example 8a7b6c5d-4e3f-2a1b-0c9d-8e7f6a5b4c3d
                 */
                categoryGroupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The new name for the category group.
                     * @example Other
                     */
                    name?: string;
                    /**
                     * @description The zero-based position of the category group.
                     * @example 2
                     */
                    position?: number;
                };
            };
        };
        responses: {
            /** @description Category group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCategoryGroupResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A category group with the requested name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid category group update request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
