/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/budget/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full budget snapshot
         * @description Fetches a snapshot containing pre-indexed entities for frontend consumption for the authenticated user.
         */
        get: operations["getBudgetSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "categoryGroups": {
         *         "user": {
         *           "cg_1": {
         *             "id": "cg_1",
         *             "name": "Food",
         *             "position": 1
         *           }
         *         },
         *         "inflow": {
         *           "id": "inflow",
         *           "name": "Inflow",
         *           "position": 0
         *         },
         *         "uncategorised": {
         *           "id": "uncategorised",
         *           "name": "Uncategorised",
         *           "position": 999
         *         }
         *       },
         *       "categories": {
         *         "user": {
         *           "cat_1": {
         *             "id": "cat_1",
         *             "name": "Groceries",
         *             "position": 1,
         *             "categoryGroupId": "cg_1"
         *           }
         *         },
         *         "rta": {
         *           "id": "rta",
         *           "name": "Ready to Assign",
         *           "position": 0,
         *           "categoryGroupId": "cg_1"
         *         },
         *         "uncategorised": {
         *           "id": "uncategorised",
         *           "name": "Uncategorised",
         *           "position": 999,
         *           "categoryGroupId": "cg_1"
         *         }
         *       },
         *       "months": {
         *         "month_1": {
         *           "id": "month_1",
         *           "categoryId": "cat_1",
         *           "month": "2025-12",
         *           "activity": 100,
         *           "assigned": 200,
         *           "available": 100
         *         }
         *       },
         *       "accounts": {
         *         "acc_1": {
         *           "id": "acc_1",
         *           "name": "Checking",
         *           "position": 1,
         *           "open": true,
         *           "type": "checking",
         *           "deletable": true,
         *           "balance": 1000
         *         }
         *       },
         *       "transactions": {
         *         "tx_1": {
         *           "id": "tx_1",
         *           "accountId": "acc_1",
         *           "categoryId": "cat_1",
         *           "payeeId": "pay_1",
         *           "date": "2025-12-13T00:00:00.000Z",
         *           "memo": "Tesco",
         *           "inflow": 0,
         *           "outflow": 12.34
         *         }
         *       },
         *       "payees": {
         *         "pay_1": {
         *           "id": "pay_1",
         *           "name": "Tesco",
         *           "origin": "USER",
         *           "defaultCategoryId": "cat_1",
         *           "includeInPayeeList": true,
         *           "automaticallyCategorisePayee": true
         *         }
         *       },
         *       "memosByMonth": {
         *         "2025-12": {
         *           "id": "memo_1",
         *           "month": "2025-12",
         *           "content": "Holiday budget"
         *         }
         *       },
         *       "monthKeys": [
         *         "2025-12"
         *       ]
         *     }
         */
        BudgetSnapshot: {
            categoryGroups: {
                user: {
                    [key: string]: components["schemas"]["CategoryGroup"];
                };
                inflow: components["schemas"]["CategoryGroup"];
                uncategorised: components["schemas"]["CategoryGroup"];
            };
            categories: {
                user: {
                    [key: string]: components["schemas"]["Category"];
                };
                rta: components["schemas"]["Category"];
                uncategorised: components["schemas"]["Category"];
            };
            months: {
                [key: string]: components["schemas"]["Month"];
            };
            accounts: {
                [key: string]: components["schemas"]["Account"];
            };
            transactions: {
                [key: string]: components["schemas"]["Transaction"];
            };
            payees: {
                [key: string]: components["schemas"]["Payee"];
            };
            /** @description Map of monthKey → memo (1:1 invariant) */
            memosByMonth: {
                [key: string]: components["schemas"]["Memo"];
            };
            monthKeys: string[];
        };
        CategoryGroup: {
            id: string;
            name: string;
            position: number;
        };
        Category: {
            id: string;
            name: string;
            position: number;
            categoryGroupId: string;
        };
        Month: {
            id: string;
            categoryId: string;
            month: string;
            activity: number;
            assigned: number;
            available: number;
        };
        Account: {
            id: string;
            name: string;
            position: number;
            open: boolean;
            /** @enum {unknown} */
            type: "BANK" | "CREDIT_CARD";
            deletable: boolean;
            balance: number;
        };
        Transaction: {
            id: string;
            accountId: string;
            categoryId?: string | null;
            payeeId?: string | null;
            /** Format: date-time */
            date: string;
            memo: string;
            inflow: number;
            outflow: number;
        };
        Payee: {
            id: string;
            name: string;
            /** @enum {unknown} */
            origin: "SYSTEM" | "USER";
            defaultCategoryId: string | null;
            includeInPayeeList: boolean;
            automaticallyCategorisePayee: boolean;
        };
        Memo: {
            id: string;
            month: string;
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBudgetSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSnapshot"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
